@echo off
cls

set DRIVE_LETTER =%1:
set GAME_PATH=%DRIVE_LETTER%/Users/WadeMcCall/Downloads/GameEngine

set CEGUI_PATH=%GAME_PATH%/cegui-0.8.7
set OGRE_PATH=%GAME_PATH%/ogre_src_v1-8-1
set BOOST_PATH=%GAME_PATH%/boost_1_63_0
set FREEIMAGE_PATH=%GAME_PATH%/FreeImage3170WIN32WIN64/lib
set ZLIB_PATH=%GAME_PATH%/zlib-1.2.11
set TDM=%GAME_PATH%/TDM-GCC-64
set TINYXML_DIR=%GAME_PATH%/tinyxml_2.6.2
set OIS_PATH=%GAME_PATH%/ois
set BASS_PATH=%GAME_PATH%/bass2.4
set LUA_PATH=%GAME_PATH%/lua
set PHYSICS_PATH=%GAME_PATH%/bullet3-2.85.1

set PATH=%TDM%/bin;%OIS_PATH%/lib;%OGRE_PATH%/build/bin;%BOOST_PATH%/stage/lib;%ZLIB_PATH%/lib;%FREEIMAGE_PATH%;c:/windows;%TINYXML_DIR%/lib;%BASS_PATH%;%CEGUI_PATH%/build/bin;%LUA_PATH%/lib;
mingw32-make CEGUI_PATH=%CEGUI_PATH% BASS_PATH=%BASS_PATH% OIS_PATH=%OIS_PATH% OGRE_PATH=%OGRE_PATH% BOOST_PATH=%BOOST_PATH% GAME_PATH=%GAME_PATH% LUA_PATH=%LUA_PATH% PHYSICS_PATH=%PHYSICS_PATH%